### ISSUE TITLE
32-bit Wheels missing

### ISSUE THREAD

**Issue by bashtage** [andfoy/pywinpty#147]
Releases prior to 1.0 had 32-bit wheels.  Are the missing 32-bit wheels by design or just an omission?  The missing wheels makes testing 32-bit Windows more challenging.

**Comment by andfoy** [comment]
Hi @bashtage, we use CI machines in order to compile the wheels, sadly, most of the services have been phasing out support for x86 architectures. Also, conda-forge doesn't support 32-bit builds anymore, so basically we dropped the support for 32 bit wheels. In this case I'd suggest to stick to the last release that did support 32-bit machines.
