### ISSUE TITLE
could there be a pywinpty wheel for pypy3.7-v7.3.5-win64.

### ISSUE THREAD

**Issue by stonebig** [andfoy/pywinpty#148]
it's tricky to try compile Pywinpty for PyPy3, apparently you need some sort of cross-compilation

**Comment by andfoy** [comment]
In theory maturin supports pypy compilation: https://github.com/PyO3/maturin#pypy, however I don't know how it does interface with the MSVC toolchain, have you tried to compile it @stonebig?

**Comment by andfoy** [comment]
It seems that conda-forge does not allow to install pypy on Windows: https://conda-forge.org/blog/posts/2020-03-10-pypy/

**Comment by andfoy** [comment]
It seems that someone is producing PyPy wheels already: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pywinpty

**Comment by stonebig** [comment]
Yes he does, now. And it's not just someone, it's the-one Christoph Gohlke that does the equivalent of pypy-forge-for-windows since 10 years+.

**Comment by mattip** [comment]
conda-forge has a windows pypy migration going at the moment to try to support pypy + windows + python3.7. This package [does not build](https://github.com/conda-forge/pywinpty-feedstock/pull/38) because it needs `maturin >= 0.11.3` but there was concern expressed on that PR that the project tried updating maturin and failed.
