### ISSUE TITLE
[Question] Messed up display buffer after resize?

### ISSUE THREAD

**Issue by matkuki** [andfoy/pywinpty#331]
Hi,

`pywinpty` works great, but I'm having issues with resizing causing the output to be garbled/messed-up.
I know this is not an exclusively `pywinpty` problem, for example `Alacritty` and `Nu-Shell` have the same problem.

Is there maybe a way to mitigate this in `pywinpty`?

Here are examples of what is happening (examples are `Alacritty`/`Nu-Shel`l, but same happens in `pywinpty`):
![alacritty_HWse3frOHW](https://github.com/andfoy/pywinpty/assets/10289651/d3f15448-b9dc-457c-83b4-18f197ddfc44)
![nu_hLrTlobKRG](https://github.com/andfoy/pywinpty/assets/10289651/1c2ac88f-bc0b-4036-9d77-448927853e7e)

**Comment by andfoy** [comment]
Hi @matkuki, thanks for opening this issue. As `pywinpty` relies on either `winpty` or the native Windows ConPTY implementation, the output is produced by their implementations, rendering `pwinpty`/`winpty-rs` as libraries that just call them.

From my limited experience, resizing will only cause a change on the next lines rather on past outputs, which means that the "correct" line size will only occur from the next output the terminal produces. This implies that handling resizing for previous outputs is a responsibility of the terminal application that is displaying the output rather than the library that produces it.

**Comment by matkuki** [comment]
@andfoy 
Thank you for the detailed description 👍
I'll post a solution to this if I find it. Closing this issue.
